Uses Uint8Array instead of Int8Array as base64.encode does not support Int8Array
With deno --version

deno 1.40.2 (release, x86_64-apple-darwin)
v8 12.1.285.6
typescript 5.3.3

Using Int8Array as a argument for base64.encode result in below error:

```
error: Uncaught (in promise) TypeError: The input must be a Uint8Array, a string, or an ArrayBuffer. Received a value of the type Int8Array.
  throw new TypeError(
        ^
    at validateBinaryLike (https://deno.land/std@0.207.0/encoding/_util.ts:24:9)
    at Module.encodeBase64 (https://deno.land/std@0.207.0/encoding/base64.ts:121:17)
```